spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:supermarket
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: false
